version: '3'
services:
  postgres:
    image: postgres:12.3
    hostname: postgres_host
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgres  #スーパーユーザ(postgres)のパスワード
      POSTGRES_USER: admin         #ユーザアカウント
      POSTGRES_PASSWORD: password  #ユーザアカウントのパスワード
      POSTGRES_DB: postgres_db     #DB名
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      DATABASE_HOST: localhost
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    user: root
    volumes:
      - ./postgres/data:/var/lib/postgresql/data    # ※ホストOSで永続化
      - ./postgres/sql:/docker-entrypoint-initdb.d  # 初期データ投入
